# Copyright 2025 The Blocked Authors. All rights reserved.

source_set("video_capture") {
  sources = [
    "blocked_video_capture_service.cc",
    "blocked_video_capture_service.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/blocked/blocked_ipc:blocked_ipc",
    "//components/keyed_service/core",
    "//content/public/common/blocked_mojom",
    "//media/capture",
    "//mojo/public/cpp/bindings",
  ]

  configs += [ "//chrome/browser/blocked:blocked_config" ]
}
