# Copyright 2025 The Blockd Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Eye tracking module for Blocked renderer process.

import("//build/config/features.gni")

source_set("blocked_eye_tracking") {
  sources = [
    "calibration_overlay.cc",
    "calibration_overlay.h",
    "eye_tracker.cc",
    "eye_tracker.h",
    "eye_tracking_worker.cc",
    "eye_tracking_worker.h",
    "face_detector.cc",
    "face_detector.h",
    "gaze_estimator.cc",
    "gaze_estimator.h",
  ]

  deps = [
    "//base",
    "//content/renderer/blocked_ipc",
    "//mojo/public/cpp/bindings",
    "//third_party/blink/public:blink",
    "//third_party/mediapipe:blocked_mediapipe",
    "//third_party/skia",
  ]

  # Allow access from content/renderer.
  visibility = [
    "//content/renderer:renderer",
  ]
}

# Unit tests
source_set("blocked_eye_tracking_unittests") {
  testonly = true

  sources = [
    "eye_tracker_unittest.cc",
    "face_detector_unittest.cc",
    "gaze_estimator_unittest.cc",
  ]

  deps = [
    ":blocked_eye_tracking",
    "//base",
    "//base/test:test_support",
    "//content/test:test_support",
    "//testing/gmock",
    "//testing/gtest",
  ]
}
