# Copyright 2025 The Blocked Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/features.gni")

source_set("blocked_home") {
  sources = [
    "blocked_home_ui.cc",
    "blocked_home_ui.h",
    "blocked_web_ui_configs.cc",
    "blocked_web_ui_configs.h",
  ]

  deps = [
    "//base",
    "//chrome/browser/resources/blocked/home:build",
    "//chrome/common",
    "//content/public/browser",
    "//content/public/common",
    "//services/network/public/mojom",
    "//ui/base",
  ]

  public_deps = [
    "//chrome/browser/resources/blocked/home:build",
  ]
}
