# Copyright 2025 The Blockd Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Video capture module for Blocked renderer process.

import("//build/config/features.gni")

source_set("blocked_video") {
  sources = [
    "camera_manager.cc",
    "camera_manager.h",
    "frame_processor.cc",
    "frame_processor.h",
    "media_stream_video_sink_impl.cc",
    "media_stream_video_sink_impl.h",
    "video_capture_client_impl.cc",
    "video_capture_client_impl.h",
    "video_capturer.cc",
    "video_capturer.h",
  ]

  deps = [
    "//base",
    "//content/renderer/blocked_ipc",
    "//media/base",
    "//mojo/public/cpp/bindings",
    "//third_party/blink/public:blink",
  ]

  # Allow access from content/renderer, eye tracking, and tests.
  visibility = [
    ":*",
    "//content/renderer:renderer",
    "//content/renderer/blocked_eye_tracking:*",
  ]
}

# Unit tests
source_set("blocked_video_unittests") {
  testonly = true

  sources = [
    "camera_manager_unittest.cc",
    "video_capturer_unittest.cc",
  ]

  deps = [
    ":blocked_video",
    "//base",
    "//base/test:test_support",
    "//content/test:test_support",
    "//testing/gmock",
    "//testing/gtest",
  ]
}
