# Copyright 2025 The Blockd Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Audio capture module for Blocked renderer process.

import("//build/config/features.gni")

source_set("blocked_audio") {
  sources = [
    "audio_capture_client_impl.cc",
    "audio_capture_client_impl.h",
    "audio_capturer.cc",
    "audio_capturer.h",
    "media_stream_audio_sink_impl.cc",
    "media_stream_audio_sink_impl.h",
    "microphone_audio_capturer.cc",
    "microphone_audio_capturer.h",
    "opus_encoder.cc",
    "opus_encoder.h",
    "tab_audio_capturer.cc",
    "tab_audio_capturer.h",
  ]

  deps = [
    "//base",
    "//content/public/common/blocked_mojom",
    "//content/renderer/blocked_ipc:blocked_ipc",
    "//media/base",
    "//mojo/public/cpp/bindings",
    "//third_party/blink/public:blink",
    "//third_party/opus",
  ]

  # Allow access from content/renderer and tests.
  visibility = [
    ":*",
    "//content/renderer:renderer",
  ]
}

# Unit tests
source_set("blocked_audio_unittests") {
  testonly = true

  sources = [
    "opus_encoder_unittest.cc",
  ]

  deps = [
    ":blocked_audio",
    "//base",
    "//base/test:test_support",
    "//testing/gmock",
    "//testing/gtest",
    "//third_party/opus",
  ]
}
